version: '8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  my-application:
    container_name: currencyConverter
    image: springboot-app
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis