version: '3'
services:
  redis-server:
    container_name: redis2
    image: redis/redis-stack
    ports:
      - "6379:6379"

  my-application:
    container_name: currencyConverter2
    image: springboot-app
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
