version: '8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  my-application:
    container_name: currencyConverter
    image: springboot-app
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my-network

networks:
    my-network:
        driver: bridge
